
title: My Resume
url: 'http://m809745357.github.com/resume'
baseurl: '/resume' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: 沈 益飞
tagline: PHP初级开发工程师
pic: https://avatars3.githubusercontent.com/u/15150683?v=3&u=2e440f0f0fe3105ecfd3b5caf3322dbbbfa44eba&s=400  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: 809745357@qq.com
phone: 183-6783-1980
website: www.xxig.com.cn #do not add http://
linkedin:
github: m809745357
twitter:

#Update all the sections by editing the files inside _includes folder.
